name: VM Auto-stop at sharp 1pm IST
trigger: none
pool: Default

schedules:
- cron: '30 7 * * *'
  displayName: Run the pipeline & stop the VM at sharp 01:00 PM IST
  branches:
    include:
      - main
  always: true

variables:
  RG_NAME: RG_EUS_VMs
  VM_NAME: vmwus01tus

stages:
- stage: VM_Auto_Stop
  displayName: VM Auto-stop
  jobs:
  - job: VM_Auto_Stop
    displayName: VM Auto-stop
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'service principle tushar'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: 'az vm deallocate --resource-group $(RG_NAME) --name $(VM_NAME)'
