name: Infrastructure_deployment pipeline

trigger: none

pool: Default

stages:
- stage: TerraformInit
  jobs:
  - job: TerraformInitJob
    displayName: Terraform Init
    steps:
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'tushar_SP'
        backendAzureRmResourceGroupName: 'Tushar_Backend'
        backendAzureRmStorageAccountName: 'ppipestoragetu2'
        backendAzureRmContainerName: 'ppipecontainer'
        backendAzureRmKey: 'infrastructuredeploy.tfstate'
