name : Infra3_yaml_pipeline_with_tfsec
trigger:
 -  main
pool: Default

stages:
-  stage: Terraform_Init_Plan
   displayName: Terraform Init & Plan
   jobs:
    -  job: Terraform_Init_Plan
       displayName: Terraform Init & Plan
       steps:
       - task: TerraformTaskV4@4
         displayName: Terraform_Init
         inputs:
           provider: 'azurerm'
           command: 'init'
           workingDirectory: '$(System.DefaultWorkingDirectory)/Practice_Codes/01.PC_20_11/01.Modules'
           backendServiceArm: 'tushar_ado_secret1'
           backendAzureRmResourceGroupName: 'Tushar_Backend'
           backendAzureRmStorageAccountName: 'ppipestoragetu46'
           backendAzureRmContainerName: 'ppipecontainer'
           backendAzureRmKey: 'infra3.tfstate'
       - task: TerraformTaskV4@4
         displayName: Terraform_fmt
         inputs:
           provider: 'azurerm'
           command: 'custom'
           workingDirectory: '$(System.DefaultWorkingDirectory)/Practice_Codes/01.PC_20_11/01.Modules'
           outputTo: 'console'
           customCommand: 'fmt'
           environmentServiceNameAzureRM: 'tushar_ado_secret1'
       - task: TerraformTaskV4@4
         displayName: Terraform_Validate
         inputs:
           provider: 'azurerm'
           command: 'validate'
           workingDirectory: '$(System.DefaultWorkingDirectory)/Practice_Codes/01.PC_20_11/01.Modules'
       - task: tfsec@1
         displayName: Tfsec_code_scanning
         inputs:
           version: 'v1.26.0'
           dir: '$(System.DefaultWorkingDirectory)/Practice_Codes/01.PC_20_11/'
       - task: TerraformTaskV4@4
         displayName: Terraform_Plan
         inputs:
           provider: 'azurerm'
           command: 'plan'
           workingDirectory: '$(System.DefaultWorkingDirectory)/Practice_Codes/01.PC_20_11/01.Modules'
           environmentServiceNameAzureRM: 'tushar_ado_secret1'

- stage: Manual_Validation
  displayName : Manual_Validation
  dependsOn : Terraform_Init_Plan
  pool : server
  jobs:
  -  job: Manual_Validation
     displayName: Manual_Validation
     steps:
     - task: ManualValidation@1
       displayName : Manual_Validation
       inputs:
         notifyUsers: 'tusharupase786@gmail.com'
         approvers: 'tusharupase786@gmail.com'
         allowApproversToApproveTheirOwnRuns: true
         instructions: 'Please check the plan & approve to further apply the plan'

- stage: Terraform_Apply
  displayName : Terraform_Apply
  dependsOn: Manual_Validation
  jobs :
  - job: Terraform_Apply
    displayName : Terraform_Apply
    steps :
    - task: TerraformTaskV4@4
      displayName: Terraform_Re-Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Practice_Codes/01.PC_20_11/01.Modules'
        backendServiceArm: 'tushar_ado_secret1'
        backendAzureRmResourceGroupName: 'Tushar_Backend'
        backendAzureRmStorageAccountName: 'ppipestoragetu46'
        backendAzureRmContainerName: 'ppipecontainer'
        backendAzureRmKey: 'infra3.tfstate'
    - task: TerraformTaskV4@4
      displayName: Terraform_Apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Practice_Codes/01.PC_20_11/01.Modules'
        environmentServiceNameAzureRM: 'tushar_ado_secret1'