name: infra2_yaml_pipeline_jobsonly
trigger:
  - main
pool: Default

jobs:
  - job: Terraform_Init_Plan
    displayName: Terraform_Init_Plan
    steps: 
    - task: TerraformTaskV4@4
      displayName: Terraform_Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Practice_Codes/01.PC_20_11/01.Modules'
        backendServiceArm: 'tushar_ado_secret1'
        backendAzureRmResourceGroupName: 'Tushar_Backend'
        backendAzureRmStorageAccountName: 'ppipestoragetu46'
        backendAzureRmContainerName: 'ppipecontainer'
        backendAzureRmKey: 'jobs.tfstate'
    - task: TerraformTaskV4@4
      displayName: Terraform_Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Practice_Codes/01.PC_20_11/01.Modules'
        environmentServiceNameAzureRM: 'tushar_ado_secret1'
  
  - job: Manual_Validation
    displayName : Manual_Validation
    dependsOn: Terraform_Init_Plan
    pool: server
    steps:
    - task: ManualValidation@1
      inputs:
        notifyUsers: 'tusharupase786@gmail.com'
        approvers: 'tusharupase786@gmail.com'
        allowApproversToApproveTheirOwnRuns: true
        instructions: 'Please check & approve the plan for further action'

  - job: Terraform_Apply
    displayName : Terraform_Apply
    dependsOn : Manual_Validation
    steps :
    - task: TerraformTaskV4@4
      displayName : Terraform_Re_Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Practice_Codes/01.PC_20_11/01.Modules'
        backendServiceArm: 'tushar_ado_secret1'
        backendAzureRmResourceGroupName: 'Tushar_Backend'
        backendAzureRmStorageAccountName: 'ppipestoragetu46'
        backendAzureRmContainerName: 'ppipecontainer'
        backendAzureRmKey: 'jobs.tfstate'
    - task: TerraformTaskV4@4
      displayName : Terraform_Apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Practice_Codes/01.PC_20_11/01.Modules'
        environmentServiceNameAzureRM: 'tushar_ado_secret1'
