---
name: New-tus-pipel-prod

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - environments/prod

pool: Default

steps:
- task: TerraformInstaller@0
  displayName: "Terraform Tool Installer"
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV4@4
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Service connection pipeline classic'
    backendAzureRmResourceGroupName: 'Donotdeletewipforpipe'
    backendAzureRmStorageAccountName: 'ppipestoragetu'
    backendAzureRmContainerName: 'ppipecontainer'
    backendAzureRmKey: 'tfprod/terraform.tfstate'
  
- task: TerraformTaskV4@4
  displayName: 'Terraform plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/environments/prod'
    environmentServiceNameAzureRM: 'Service connection pipeline classic'

- task: TerraformTaskV4@4
  displayName: 'Terraform Apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/environments/prod'
    environmentServiceNameAzureRM: 'Service connection pipeline classic'
